Repository ucsb-cs156-w24/proj-gauchoride-w24-7pm-1, pull requests merged in 2024-03, with the labels that each got.

#26 OP - FEATURE: Fix typo in navbar #93
  frontend/src/main/components/Nav/AppNavbar.js
Labels: FIXME - Need peer CR

#29 OP - FEATURE: All users should not see "Apply to be a rider" if they are a rider #9
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/gauchoride/interceptors/RoleInterceptorTests.java
Labels: Merge Candidate, 5

#33 OP - FEATURE: Change confusing ride request field names #94
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/tests/components/Ride/RideForm.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
Labels: Merge Candidate, 5

#35 James - Add DB record and fixtures for Driver Availability
  frontend/src/fixtures/driverAvailabilityFixtures.js
  src/main/java/edu/ucsb/cs156/gauchoride/entities/DriverAvailability.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverAvailabilityRepository.java
Labels: Merge Candidate, 10

#37 Added the RiderApplicationShowPage
  frontend/src/App.js
  frontend/src/main/components/RiderApplication/RiderApplicationShowForm.js
  frontend/src/main/pages/RiderApplication/RiderApplicationShowPageMember.js
  frontend/src/stories/components/RiderApplication/RiderApplicationShowForm.stories.js
  frontend/src/tests/components/RiderApplication/RiderApplicationShowForm.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPage.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationShowPage.test.js
Labels: Merge Candidate, 10

#39 Add Driver Availability Form + Tests
  frontend/src/main/components/Driver/DriverAvailabilityForm.js
  frontend/src/stories/components/Driver/DriverAvailabilityForm.stories.js
  frontend/src/tests/components/Driver/DriverAvailabilityForm.test.js
Labels: Merge Candidate, FIXME - Need peer CR, 10

#42 LR driver availability controller
  frontend/package-lock.json
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityController.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/DriverAvailabilityRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/DriverAvailabilityControllerTests.java
Labels: Merge Candidate, 10

#46 ZP - Added Rider Application Buttons to Change the Status
  frontend/src/main/components/RiderApplication/RiderApplicationEditForm.js
  frontend/src/main/components/RiderApplication/RiderApplicationShowForm.js
  frontend/src/main/pages/RiderApplication/RiderApplicationEditPageAdmin.js
  frontend/src/main/pages/RiderApplication/RiderApplicationEditPageMember.js
  frontend/src/tests/components/RiderApplication/RiderApplicationEditForm.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPage.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationEditPageAdmin.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationShowPage.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RiderApplicationControllerTests.java
Labels: 10

#50 James - Driver Availability Pages, Stories, Tests
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Drivers/DriverAvailabilityCreatePage.js
  frontend/src/main/pages/Drivers/DriverAvailabilityEditPage.js
  frontend/src/main/pages/Drivers/DriverAvailabilityIndexPage.js
  frontend/src/stories/pages/Driver/DriverAvailabilityCreatePage.stories.js
  frontend/src/stories/pages/Driver/DriverAvailabilityEditPage.stories.js
  frontend/src/stories/pages/Driver/DriverAvailabilityIndexPage.stories.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityCreatePage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityEditPage.test.js
  frontend/src/tests/pages/Drivers/DriverAvailabilityIndexPage.test.js
Labels: 20

#49 Limit the displayed element in the ShowRiderApplyPage
  frontend/src/main/components/RiderApplication/RiderApplicationShowForm.js
  frontend/src/tests/components/RiderApplication/RiderApplicationShowForm.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationShowPage.test.js
  frontend/src/tests/pages/RiderApplication/RiderApplicationShowPageMember.test.js
Labels: 5
